#!/bin/sh

# Set these paths appropriately

BIN=/private/var/www/himhacks/timelines/tagging/app/lib/treetagger/bin
CMD=/private/var/www/himhacks/timelines/tagging/app/lib/treetagger/cmd
LIB=/private/var/www/himhacks/timelines/tagging/app/lib/treetagger/lib

OPTIONS="-token -lemma -sgml"

TOKENIZER=${CMD}/utf8-tokenize.perl
TAGGER=${BIN}/tree-tagger
ABBR_LIST=${LIB}/catalan-abbreviations
PARFILE=${LIB}/catalan-utf8.par

$TOKENIZER -c -a $ABBR_LIST $* |
$TAGGER $OPTIONS $PARFILE
