#!/bin/sh

# Set these paths appropriately

BIN=/private/var/www/himhacks/timelines/tagging/app/lib/treetagger/bin
CMD=/private/var/www/himhacks/timelines/tagging/app/lib/treetagger/cmd
LIB=/private/var/www/himhacks/timelines/tagging/app/lib/treetagger/lib

OPTIONS="-token -lemma -sgml"

TOKENIZER=${CMD}/utf8-tokenize.perl
TAGGER=${BIN}/tree-tagger
ABBR_LIST=${LIB}/romanian-abbreviations
PARFILE=${LIB}/romanian-utf8.par

$TOKENIZER -r -a $ABBR_LIST $* |
${CMD}/split-romanian.perl ${LIB}/romanian-tokens |
$TAGGER $OPTIONS $PARFILE
