#!/bin/sh

# Set these paths appropriately

BIN=/Users/kochhar/workspace/projects/timelines/tagging/app/lib/treetagger/bin
CMD=/Users/kochhar/workspace/projects/timelines/tagging/app/lib/treetagger/cmd
LIB=/Users/kochhar/workspace/projects/timelines/tagging/app/lib/treetagger/lib

OPTIONS="-token -lemma -sgml"

TOKENIZER=${CMD}/utf8-tokenize.perl
MWL=${CMD}/mwl-lookup.perl
TAGGER=${BIN}/tree-tagger
ABBR_LIST=${LIB}/galician-abbreviations-utf8
PARFILE=${LIB}/galician-utf8.par
MWLFILE=${LIB}/galician-mwls

$TOKENIZER -z -a $ABBR_LIST $* |
# recognition of MWLs
$MWL -f $MWLFILE |
# tagging
$TAGGER $OPTIONS $PARFILE
