#!/bin/sh

# Set these paths appropriately

BIN=/Users/kochhar/workspace/projects/timelines/tagging/app/lib/treetagger/bin
CMD=/Users/kochhar/workspace/projects/timelines/tagging/app/lib/treetagger/cmd
LIB=/Users/kochhar/workspace/projects/timelines/tagging/app/lib/treetagger/lib

OPTIONS="-token -lemma -sgml"

TAGGER=${BIN}/tree-tagger
TOKENIZER=${CMD}/tokenize-korean.pl
PARFILE=${LIB}/korean-utf8.par

$TOKENIZER $* |
$TAGGER $OPTIONS $PARFILE |
$CMD/add-korean-sentence-markers.pl |
$CMD/reformat-korean-tagger-output.pl
