#!/bin/sh

# Set these paths appropriately

BIN=/Users/kochhar/workspace/projects/timelines/tagging/app/lib/treetagger/bin
CMD=/Users/kochhar/workspace/projects/timelines/tagging/app/lib/treetagger/cmd
LIB=/Users/kochhar/workspace/projects/timelines/tagging/app/lib/treetagger/lib

OPTIONS="-token -lemma -sgml"

TOKENIZER=${CMD}/utf8-tokenize.perl
TAGGER=${BIN}/tree-tagger
PARFILE=${LIB}/russian-utf8.par

# do tokenization
$TOKENIZER $* |
$TAGGER $OPTIONS $PARFILE
