#!/bin/sh

# Set these paths appropriately

BIN=/private/var/www/himhacks/timelines/tagging/app/lib/treetagger/bin
CMD=/private/var/www/himhacks/timelines/tagging/app/lib/treetagger/cmd
LIB=/private/var/www/himhacks/timelines/tagging/app/lib/treetagger/lib

OPTIONS="-token -lemma -sgml"

TOKENIZER=${CMD}/utf8-tokenize.perl
MWL=${CMD}/mwl-lookup.perl
TAGGER=${BIN}/tree-tagger
ABBR_LIST=${LIB}/latin-abbreviations
PARFILE=${LIB}/latin.par
MWLFILE=${LIB}/latin-mwls

$TOKENIZER -a $ABBR_LIST $* |
# recognition of MWLs
$MWL -f $MWLFILE |
# tagging
$TAGGER $OPTIONS $PARFILE

