#!/bin/sh

# Set these paths appropriately

BIN=/private/var/www/himhacks/timelines/tagging/app/lib/treetagger/bin
CMD=/private/var/www/himhacks/timelines/tagging/app/lib/treetagger/cmd
LIB=/private/var/www/himhacks/timelines/tagging/app/lib/treetagger/lib

OPTIONS="-token -lemma -sgml"

TAGGER=${BIN}/tree-tagger
TOKENIZER=${CMD}/utf8-tokenize.perl
ABBR_LIST=${LIB}/dutch-abbreviations
PARFILE=${LIB}/dutch-utf8.par

$TOKENIZER -a $ABBR_LIST $* |
$TAGGER $OPTIONS $PARFILE
