#!/bin/sh

# Set these paths appropriately

BIN=/private/var/www/himhacks/timelines/tagging/app/lib/treetagger/bin
CMD=/private/var/www/himhacks/timelines/tagging/app/lib/treetagger/cmd
LIB=/private/var/www/himhacks/timelines/tagging/app/lib/treetagger/lib

OPTIONS="-token -lemma -sgml"

TOKENIZER=${CMD}/utf8-tokenize.perl
MWL=${CMD}/greek-mwls.pl
TAGGER=${BIN}/tree-tagger
ABBR_LIST=${LIB}/greek-abbreviations-utf8
PARFILE=${LIB}/greek-utf8.par

$TOKENIZER -a $ABBR_LIST $* |
$MWL |
# tagging
$TAGGER $OPTIONS $PARFILE

