#!/bin/sh

# Set these paths appropriately

BIN=/Users/kochhar/workspace/projects/timelines/tagging/app/lib/treetagger/bin
CMD=/Users/kochhar/workspace/projects/timelines/tagging/app/lib/treetagger/cmd
LIB=/Users/kochhar/workspace/projects/timelines/tagging/app/lib/treetagger/lib

OPTIONS="-token -lemma -sgml"

TAGGER=${BIN}/tree-tagger
TOKENIZER=${CMD}/tokenize.pl
ABBR_LIST=${LIB}/swahili-abbreviations
PARFILE=${LIB}/swahili.par

$TOKENIZER -a $ABBR_LIST $* |
$TAGGER $OPTIONS $PARFILE
