#!/bin/sh

# Set these paths appropriately

BIN=/Users/kochhar/workspace/projects/timelines/tagging/app/lib/treetagger/bin
CMD=/Users/kochhar/workspace/projects/timelines/tagging/app/lib/treetagger/cmd
LIB=/Users/kochhar/workspace/projects/timelines/tagging/app/lib/treetagger/lib

OPTIONS="-token -lemma -sgml"

TAGGER=${BIN}/tree-tagger
TOKENIZER=${CMD}/utf8-tokenize.perl
PARFILE=${LIB}/slovenian-utf8.par

$TOKENIZER $* |
$TAGGER $OPTIONS $PARFILE
